name: Run AQAvit

on:
  workflow_dispatch: # Allows the job to be manually triggered
    inputs:
      customizedSdkUrl:
        description: SDK URL
        required: true
      aqaTestsRepo:
        description: Adoptium aqa-tests repository # Make sure this branch is set to the latest release branch
        default: 'adoptium/aqa-tests:v0.9.7-release'
        required: true
      runner:
        description: GitHub runner
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

env:  # Links to the JDK build under test and the native test libs
  USE_TESTENV_PROPERTIES: true
  CUSTOMIZED_SDK_URL: ${{ inputs.customizedSdkUrl }}

jobs:
  run_aqa:
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        target: [sanity, extended]
        suite: [functional, openjdk, system, perf]
        include:
          - target: special
            suite: functional

    steps:

    - name: Run AQA Tests - ${{ matrix.target }}.${{ matrix.suite }}
      uses: adoptium/run-aqa@v2.0.1
      with:
        jdksource: 'customized'
        customizedSdkUrl: ${{ env.CUSTOMIZED_SDK_URL }}
        aqa-testsRepo: ${{ inputs.aqaTestsRepo }} # Make sure this branch is set to the latest release branch
        build_list: ${{ matrix.suite }}
        target: _${{ matrix.target }}.${{ matrix.suite }}

    - uses: actions/upload-artifact@v2
      if: always() # Always run this step (even if the tests failed)
      with:
        name: test_output
        path: ./**/output_*/*.tap
